--Bring all configuration files from lua folder
require('nguyen/telescope')
require('nguyen/lightline')
require('nguyen/treesitter')
require('nguyen/lsp')
require('nguyen/lspconfig')
require('nguyen/gitsigns')
require('nguyen/trouble')
require('nguyen/nvterm')
require('nguyen/comment')
